### ISSUE TITLE
Initialization issue upon startup

### ISSUE THREAD

**Issue by tdalianis** [kevoree/kevoree-library#23]
There are times (it happens in random) when i start a kevoree node (mvn kev:run) that when it reaches the point that initializes the groups and channels the initialization simply freezes and i have to abort.
If I remove the declarations of the channels from the kev script it always starts the kevoree node without issues.  

Any ideas?

**Comment by maxleiko** [comment]
This should be fixed by https://github.com/dukeboard/kevoree-classloading-framework/commit/e188f2cadf35e479abad28e05f651ed692130b97  
This fix should also resolve #19 issue

**Comment by tdalianis** [comment]
I think the issue still continues at least when docker is involved. I start a new container with a node that is the masterNode of the group and sometimes it seems to stuck when it tries to initialize the groups and then fails. I have noticed this also when i restarted the docker container.

heads@heads-vm:~/kevoree/atcMainHeads$ docker run --restart=always --name master -v /home/heads/.kevoree/config.json:/root/.kevoree/config.json  -v /home/heads/kevoree:/opt/kevoree -v /home/heads/.m2:/root/.m2 -t -p 9000:9000 kevoree/java  -Dversion=5.4.0-SNAPSHOT -Dnode.name=masterNode -Dnode.bootstrap=/opt/kevoree/main.kevs
00:00 INFO: Kevoree bootstrap from mvn:org.kevoree:org.kevoree.bootstrap:5.4.0-SNAPSHOT
00:03 INFO: Log level= INFO
00:03 INFO: Registry https://kevoree.braindead.fr:443
00:03 INFO: Starting Kevoree using version: 5.4.0-SNAPSHOT
00:03 INFO: Platform node name: masterNode
00:04 INFO: Found kevoree.JavaNode/1/LATEST in the registry
00:04 INFO: Found atc.Observer/1/LATEST in the registry
00:04 INFO: Found atc.TestProcessor/4/LATEST in the registry
00:04 INFO: Found atc.MasterObserver/1/LATEST in the registry
00:04 INFO: Found kevoree.WSGroup/1/LATEST in the registry
00:05 INFO: Found kevoree.RemoteWSChan/1/LATEST in the registry
00:05 INFO: Resolving ............. org.kevoree.library.java:org.kevoree.library.java.javaNode:5.4.0-SNAPSHOT
00:06 INFO: Resolved in 1498ms
00:07 INFO: Starting /nodes[masterNode]
00:07 INFO: Comparing models and planning adaptation
00:07 INFO: Launching adaptation of the system
00:07 INFO: Resolving ............. gr.atc.heads:atcMainHeads:1.1.0-SNAPSHOT
00:10 INFO: Resolved in 3849ms
00:10 INFO: Resolving ............. org.kevoree.library.java:org.kevoree.library.java.ws:5.4.0-SNAPSHOT
00:12 INFO: Resolved in 1400ms
00:12 INFO: Add instance /nodes[masterNode]/components[masterObserver]
00:12 INFO: Add instance /groups[sync]
00:12 INFO: Add instance /hubs[observerMasterChannel]
00:12 INFO: Add instance /hubs[masterObserverChannel]
00:12 INFO: Bind /nodes[masterNode]/components[masterObserver]/provided[receiveMessage] /hubs[observerMasterChannel]
00:12 INFO: Bind /nodes[masterNode]/components[masterObserver]/required[outputPort] /hubs[masterObserverChannel]
00:12 INFO: Starting /nodes[masterNode]/components[masterObserver]
00:12 INFO: MasterObserver starts
00:12 INFO: Starting /hubs[observerMasterChannel]
00:12 INFO: Starting /hubs[masterObserverChannel]
00:12 INFO: Starting /groups[sync]
00:42 ERROR: Error while executing primitive command StartStopInstance sync start
00:42 WARN: JavaSENode is aborting last update...
00:42 WARN: JavaSENode update aborted in 35371 ms
00:42 INFO: End deploy result=false (35368ms)
00:42 INFO: Bootstrap failed

00:42 INFO: Stopping Kevoree
00:42 ERROR: Unable to find node platform "masterNode" in current model. Cannot correctly stop platform
00:42 INFO: Stopping /nodes[masterNode]
00:42 INFO: Kevoree core stopped
00:42 INFO: Stopped.

**Comment by maxleiko** [comment]
Can you give me a light version (just the node & group) of the KevScript you used in order for me to try to re-create the issue.

**Comment by maxleiko** [comment]
*re-opening while investigating*

**Comment by maxleiko** [comment]
@tdalianis can you provide what's necessary to reproduce this?

**Comment by maxleiko** [comment]
Closing this as I am unable to reproduce it.
